name: Build and Release EXE

on:
  push:
    branches:
      - main

permissions:
  contents: write

jobs:
  build:
    name: Generate EXE
    runs-on: windows-latest
    steps:
      - name: Checkout Code
        uses: actions/checkout@v4

      - name: Setup Python
        uses: actions/setup-python@v4
        with:
          python-version: '3.x'

      - name: Install Dependencies
        run: |
          python -m pip install --upgrade pip
          pip install -r requirements.txt
          pip install pyinstaller

      - name: Build Executable
        run: pyinstaller --onefile --hidden-import=win32timezone --name downloader src/main.py

      - name: Upload EXE
        uses: actions/upload-artifact@v4
        with:
          name: downloader
          path: dist/downloader.exe

  release:
    name: Release EXE
    needs: build
    runs-on: ubuntu-latest
    steps:
      - name: Checkout Code
        uses: actions/checkout@v4

      - name: Download EXE from Build
        uses: actions/download-artifact@v4
        with:
          name: downloader

      - name: Create Release
        uses: softprops/action-gh-release@v2
        with:
          files: downloader.exe
          tag_name: ${{ github.ref_name }}
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
